package:
  name: sedstacker 
  version: 0.1.0_iris

build:
  number: 3

  preserve_egg_dir: yes

requirements:
  run:
   - setuptools
   - python 2.7.*
   - astlib
   - numpy 1.8.*

  build:
   - setuptools
   - python 2.7.*
   - numpy

about:
  home: https://github.com/jbudynk/sedstacker
  summary: Python library for stacking Spectral Energy Distributions
